
[[OffsetPointer]]
Address = 0x00FB18
Offset = 0x000004

[[OffsetPointer]]
Address = 0x00FCC8
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03B638
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03B6E0
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03DC9C
Offset = 0x000004

[[List]]
Name = '''songnames'''
0 = [
    '''mus_dummy''',
    '''se_use_item''',
    '''se_pc_login''',
    '''se_pc_off''',
    '''se_pc_on''',
    '''se_select''',
    '''se_win_open''',
    '''se_wall_hit''',
    '''se_door''',
    '''se_exit''',
    '''se_ledge''',
    '''se_bike_bell''',
    '''se_not_effective''',
    '''se_effective''',
    '''se_super_effective''',
    '''se_ball_open''',
    '''se_faint''',
    '''se_flee''',
    '''se_sliding_door''',
    '''se_ship''',
    '''se_bang''',
    '''se_pin''',
    '''se_boo''',
    '''se_ball''',
    '''se_contest_place''',
    '''se_a''',
    '''se_i''',
    '''se_u''',
    '''se_e''',
    '''se_o''',
    '''se_n''',
    '''se_success''',
    '''se_failure''',
    '''se_exp''',
    '''se_bike_hop''',
    '''se_switch''',
    '''se_click''',
    '''se_fu_zaku''',
    '''se_contest_condition_lose''',
    '''se_lavaridge_fall_warp''',
    '''se_ice_stairs''',
    '''se_ice_break''',
    '''se_ice_crack''',
    '''se_fall''',
    '''se_unlock''',
    '''se_warp_in''',
    '''se_warp_out''',
    '''se_repel''',
    '''se_rotating_gate''',
    '''se_truck_move''',
    '''se_truck_stop''',
    '''se_truck_unload''',
    '''se_truck_door''',
    '''se_berry_blender''',
    '''se_card''',
    '''se_save''',
    '''se_ball_bounce_1''',
    '''se_ball_bounce_2''',
    '''se_ball_bounce_3''',
    '''se_ball_bounce_4''',
    '''se_ball_trade''',
    '''se_ball_throw''',
    '''se_note_c''',
    '''se_note_d''',
    '''se_note_e''',
    '''se_note_f''',
    '''se_note_g''',
    '''se_note_a''',
    '''se_note_b''',
    '''se_note_c_high''',
    '''se_puddle''',
    '''se_bridge_walk''',
    '''se_itemfinder''',
    '''se_ding_dong''',
    '''se_balloon_red''',
    '''se_balloon_blue''',
    '''se_balloon_yellow''',
    '''se_breakable_door''',
    '''se_mud_ball''',
    '''se_field_poison''',
    '''se_escalator''',
    '''se_thunderstorm''',
    '''se_thunderstorm_stop''',
    '''se_downpour''',
    '''se_downpour_stop''',
    '''se_rain''',
    '''se_rain_stop''',
    '''se_thunder''',
    '''se_thunder2''',
    '''se_elevator''',
    '''se_low_health''',
    '''se_exp_max''',
    '''se_roulette_ball''',
    '''se_roulette_ball2''',
    '''se_taillow_wing_flap''',
    '''se_shop''',
    '''se_contest_heart''',
    '''se_contest_curtain_rise''',
    '''se_contest_curtain_fall''',
    '''se_contest_icon_change''',
    '''se_contest_icon_clear''',
    '''se_contest_mons_turn''',
    '''se_shiny''',
    '''se_intro_blast''',
    '''se_mugshot''',
    '''se_applause''',
    '''se_vend''',
    '''se_orb''',
    '''se_dex_scroll''',
    '''se_dex_page''',
    '''se_pokenav_on''',
    '''se_pokenav_off''',
    '''se_dex_search''',
    '''se_egg_hatch''',
    '''se_ball_tray_enter''',
    '''se_ball_tray_ball''',
    '''se_ball_tray_exit''',
    '''se_glass_flute''',
    '''mus_stop''',
    '''mus_littleroot_test''',
    '''mus_gsc_route38''',
    '''mus_caught''',
    '''mus_victory_wild''',
    '''mus_victory_gym_leader''',
    '''mus_victory_league''',
    '''mus_c_comm_center''',
    '''mus_gsc_pewter''',
    '''mus_c_vs_legend_beast''',
    '''mus_route101''',
    '''mus_route110''',
    '''mus_route120''',
    '''mus_petalburg''',
    '''mus_oldale''',
    '''mus_gym''',
    '''mus_surf''',
    '''mus_petalburg_woods''',
    '''mus_level_up''',
    '''mus_heal''',
    '''mus_obtain_badge''',
    '''mus_obtain_item''',
    '''mus_evolved''',
    '''mus_obtain_tmhm''',
    '''mus_lilycove_museum''',
    '''mus_route122''',
    '''mus_oceanic_museum''',
    '''mus_evolution_intro''',
    '''mus_evolution''',
    '''mus_move_deleted''',
    '''mus_encounter_girl''',
    '''mus_encounter_male''',
    '''mus_abandoned_ship''',
    '''mus_fortree''',
    '''mus_birch_lab''',
    '''mus_b_tower''',
    '''mus_encounter_swimmer''',
    '''mus_cave_of_origin''',
    '''mus_obtain_berry''',
    '''mus_awaken_legend''',
    '''mus_slots_jackpot''',
    '''mus_slots_win''',
    '''mus_too_bad''',
    '''mus_roulette''',
    '''mus_link_contest_p1''',
    '''mus_link_contest_p2''',
    '''mus_link_contest_p3''',
    '''mus_link_contest_p4''',
    '''mus_encounter_rich''',
    '''mus_verdanturf''',
    '''mus_rustboro''',
    '''mus_poke_center''',
    '''mus_route104''',
    '''mus_route119''',
    '''mus_cycling''',
    '''mus_poke_mart''',
    '''mus_littleroot''',
    '''mus_mt_chimney''',
    '''mus_encounter_female''',
    '''mus_lilycove''',
    '''mus_route111''',
    '''mus_help''',
    '''mus_underwater''',
    '''mus_victory_trainer''',
    '''mus_title''',
    '''mus_intro''',
    '''mus_encounter_may''',
    '''mus_encounter_intense''',
    '''mus_encounter_cool''',
    '''mus_route113''',
    '''mus_encounter_aqua''',
    '''mus_follow_me''',
    '''mus_encounter_brendan''',
    '''mus_ever_grande''',
    '''mus_encounter_suspicious''',
    '''mus_victory_aqua_magma''',
    '''mus_cable_car''',
    '''mus_game_corner''',
    '''mus_dewford''',
    '''mus_safari_zone''',
    '''mus_victory_road''',
    '''mus_aqua_magma_hideout''',
    '''mus_sailing''',
    '''mus_mt_pyre''',
    '''mus_slateport''',
    '''mus_mt_pyre_exterior''',
    '''mus_school''',
    '''mus_hall_of_fame''',
    '''mus_fallarbor''',
    '''mus_sealed_chamber''',
    '''mus_contest_winner''',
    '''mus_contest''',
    '''mus_encounter_magma''',
    '''mus_intro_battle''',
    '''mus_weather_kyogre''',
    '''mus_weather_groudon''',
    '''mus_sootopolis''',
    '''mus_contest_results''',
    '''mus_hall_of_fame_room''',
    '''mus_trick_house''',
    '''mus_encounter_twins''',
    '''mus_encounter_elite_four''',
    '''mus_encounter_hiker''',
    '''mus_contest_lobby''',
    '''mus_encounter_interviewer''',
    '''mus_encounter_champion''',
    '''mus_credits''',
    '''mus_end''',
    '''mus_vs_wild''',
    '''mus_vs_aqua_magma''',
    '''mus_vs_trainer''',
    '''mus_vs_gym_leader''',
    '''mus_vs_champion''',
    '''mus_vs_regi''',
    '''mus_vs_kyogre_groudon''',
    '''mus_vs_rival''',
    '''mus_vs_elite_four''',
    '''mus_vs_aqua_magma_leader''',
]

[[GotoShortcut]]
Name = '''Pokemon'''
Image = '''graphics.pokemon.sprites.front/350/sprite/'''
Destination = '''data.pokemon.stats/1'''

[[GotoShortcut]]
Name = '''Trainers'''
Image = '''graphics.trainers.sprites.front/3/sprite/'''
Destination = '''data.trainers.stats'''

[[GotoShortcut]]
Name = '''Moves'''
Image = '''graphics.moves.particles.sprites/55/ptr/'''
Destination = '''data.pokemon.moves.stats.battle'''

[[GotoShortcut]]
Name = '''Items'''
Image = '''graphics.overworld.sprites/59/data/0/sprites/0/sprite/'''
Destination = '''data.items.stats'''

[[GotoShortcut]]
Name = '''Maps'''
Image = '''data.maps.banks/0/maps/9/map/0/layout/0/blockmap/'''
Destination = '''maps.0-9 (LITTLEROOTTOWN)'''
