
[[OffsetPointer]]
Address = 0x00FB18
Offset = 0x000004

[[OffsetPointer]]
Address = 0x00FCC8
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03B638
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03B6E0
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03DC9C
Offset = 0x000004

[[List]]
Name = '''songnames'''
0 = '''mus_dummy'''
1 = '''se_use_item'''
2 = '''se_pc_login'''
3 = '''se_pc_off'''
4 = '''se_pc_on'''
5 = '''se_select'''
6 = '''se_win_open'''
7 = '''se_wall_hit'''
8 = '''se_door'''
9 = '''se_exit'''
10 = '''se_ledge'''
11 = '''se_bike_bell'''
12 = '''se_not_effective'''
13 = '''se_effective'''
14 = '''se_super_effective'''
15 = '''se_ball_open'''
16 = '''se_faint'''
17 = '''se_flee'''
18 = '''se_sliding_door'''
19 = '''se_ship'''
20 = '''se_bang'''
21 = '''se_pin'''
22 = '''se_boo'''
23 = '''se_ball'''
24 = '''se_contest_place'''
25 = '''se_a'''
26 = '''se_i'''
27 = '''se_u'''
28 = '''se_e'''
29 = '''se_o'''
30 = '''se_n'''
31 = '''se_success'''
32 = '''se_failure'''
33 = '''se_exp'''
34 = '''se_bike_hop'''
35 = '''se_switch'''
36 = '''se_click'''
37 = '''se_fu_zaku'''
38 = '''se_contest_condition_lose'''
39 = '''se_lavaridge_fall_warp'''
40 = '''se_ice_stairs'''
41 = '''se_ice_break'''
42 = '''se_ice_crack'''
43 = '''se_fall'''
44 = '''se_unlock'''
45 = '''se_warp_in'''
46 = '''se_warp_out'''
47 = '''se_repel'''
48 = '''se_rotating_gate'''
49 = '''se_truck_move'''
50 = '''se_truck_stop'''
51 = '''se_truck_unload'''
52 = '''se_truck_door'''
53 = '''se_berry_blender'''
54 = '''se_card'''
55 = '''se_save'''
56 = '''se_ball_bounce_1'''
57 = '''se_ball_bounce_2'''
58 = '''se_ball_bounce_3'''
59 = '''se_ball_bounce_4'''
60 = '''se_ball_trade'''
61 = '''se_ball_throw'''
62 = '''se_note_c'''
63 = '''se_note_d'''
64 = '''se_note_e'''
65 = '''se_note_f'''
66 = '''se_note_g'''
67 = '''se_note_a'''
68 = '''se_note_b'''
69 = '''se_note_c_high'''
70 = '''se_puddle'''
71 = '''se_bridge_walk'''
72 = '''se_itemfinder'''
73 = '''se_ding_dong'''
74 = '''se_balloon_red'''
75 = '''se_balloon_blue'''
76 = '''se_balloon_yellow'''
77 = '''se_breakable_door'''
78 = '''se_mud_ball'''
79 = '''se_field_poison'''
80 = '''se_escalator'''
81 = '''se_thunderstorm'''
82 = '''se_thunderstorm_stop'''
83 = '''se_downpour'''
84 = '''se_downpour_stop'''
85 = '''se_rain'''
86 = '''se_rain_stop'''
87 = '''se_thunder'''
88 = '''se_thunder2'''
89 = '''se_elevator'''
90 = '''se_low_health'''
91 = '''se_exp_max'''
92 = '''se_roulette_ball'''
93 = '''se_roulette_ball2'''
94 = '''se_taillow_wing_flap'''
95 = '''se_shop'''
96 = '''se_contest_heart'''
97 = '''se_contest_curtain_rise'''
98 = '''se_contest_curtain_fall'''
99 = '''se_contest_icon_change'''
100 = '''se_contest_icon_clear'''
101 = '''se_contest_mons_turn'''
102 = '''se_shiny'''
103 = '''se_intro_blast'''
104 = '''se_mugshot'''
105 = '''se_applause'''
106 = '''se_vend'''
107 = '''se_orb'''
108 = '''se_dex_scroll'''
109 = '''se_dex_page'''
110 = '''se_pokenav_on'''
111 = '''se_pokenav_off'''
112 = '''se_dex_search'''
113 = '''se_egg_hatch'''
114 = '''se_ball_tray_enter'''
115 = '''se_ball_tray_ball'''
116 = '''se_ball_tray_exit'''
117 = '''se_glass_flute'''
118 = '''se_m_thunderbolt'''
119 = '''se_m_thunderbolt2'''
120 = '''se_m_harden'''
121 = '''se_m_nightmare'''
122 = '''se_m_vital_throw'''
123 = '''se_m_vital_throw2'''
124 = '''se_m_bubble'''
125 = '''se_m_bubble2'''
126 = '''se_m_bubble3'''
127 = '''se_m_rain_dance'''
128 = '''se_m_cut'''
129 = '''se_m_string_shot'''
130 = '''se_m_string_shot2'''
131 = '''se_m_rock_throw'''
132 = '''se_m_gust'''
133 = '''se_m_gust2'''
134 = '''se_m_double_slap'''
135 = '''se_m_double_team'''
136 = '''se_m_razor_wind'''
137 = '''se_m_icy_wind'''
138 = '''se_m_thunder_wave'''
139 = '''se_m_comet_punch'''
140 = '''se_m_mega_kick'''
141 = '''se_m_mega_kick2'''
142 = '''se_m_crabhammer'''
143 = '''se_m_jump_kick'''
144 = '''se_m_flame_wheel'''
145 = '''se_m_flame_wheel2'''
146 = '''se_m_flamethrower'''
147 = '''se_m_fire_punch'''
148 = '''se_m_toxic'''
149 = '''se_m_sacred_fire'''
150 = '''se_m_sacred_fire2'''
151 = '''se_m_ember'''
152 = '''se_m_take_down'''
153 = '''se_m_blizzard'''
154 = '''se_m_blizzard2'''
155 = '''se_m_scratch'''
156 = '''se_m_vicegrip'''
157 = '''se_m_wing_attack'''
158 = '''se_m_fly'''
159 = '''se_m_sand_attack'''
160 = '''se_m_razor_wind2'''
161 = '''se_m_bite'''
162 = '''se_m_headbutt'''
163 = '''se_m_surf'''
164 = '''se_m_hydro_pump'''
165 = '''se_m_whirlpool'''
166 = '''se_m_horn_attack'''
167 = '''se_m_tail_whip'''
168 = '''se_m_mist'''
169 = '''se_m_poison_powder'''
170 = '''se_m_bind'''
171 = '''se_m_dragon_rage'''
172 = '''se_m_sing'''
173 = '''se_m_perish_song'''
174 = '''se_m_pay_day'''
175 = '''se_m_dig'''
176 = '''se_m_dizzy_punch'''
177 = '''se_m_self_destruct'''
178 = '''se_m_explosion'''
179 = '''se_m_absorb_2'''
180 = '''se_m_absorb'''
181 = '''se_m_screech'''
182 = '''se_m_bubble_beam'''
183 = '''se_m_bubble_beam2'''
184 = '''se_m_supersonic'''
185 = '''se_m_belly_drum'''
186 = '''se_m_metronome'''
187 = '''se_m_bonemerang'''
188 = '''se_m_lick'''
189 = '''se_m_psybeam'''
190 = '''se_m_faint_attack'''
191 = '''se_m_swords_dance'''
192 = '''se_m_leer'''
193 = '''se_m_swagger'''
194 = '''se_m_swagger2'''
195 = '''se_m_heal_bell'''
196 = '''se_m_confuse_ray'''
197 = '''se_m_snore'''
198 = '''se_m_brick_break'''
199 = '''se_m_giga_drain'''
200 = '''se_m_psybeam2'''
201 = '''se_m_solar_beam'''
202 = '''se_m_petal_dance'''
203 = '''se_m_teleport'''
204 = '''se_m_minimize'''
205 = '''se_m_sketch'''
206 = '''se_m_swift'''
207 = '''se_m_reflect'''
208 = '''se_m_barrier'''
209 = '''se_m_detect'''
210 = '''se_m_lock_on'''
211 = '''se_m_moonlight'''
212 = '''se_m_charm'''
213 = '''se_m_charge'''
214 = '''se_m_strength'''
215 = '''se_m_hyper_beam'''
216 = '''se_m_waterfall'''
217 = '''se_m_reversal'''
218 = '''se_m_acid_armor'''
219 = '''se_m_sandstorm'''
220 = '''se_m_tri_attack'''
221 = '''se_m_tri_attack2'''
222 = '''se_m_encore'''
223 = '''se_m_encore2'''
224 = '''se_m_baton_pass'''
225 = '''se_m_milk_drink'''
226 = '''se_m_attract'''
227 = '''se_m_attract2'''
228 = '''se_m_morning_sun'''
229 = '''se_m_flatter'''
230 = '''se_m_sand_tomb'''
231 = '''se_m_grasswhistle'''
232 = '''se_m_spit_up'''
233 = '''se_m_dive'''
234 = '''se_m_earthquake'''
235 = '''se_m_twister'''
236 = '''se_m_sweet_scent'''
237 = '''se_m_yawn'''
238 = '''se_m_sky_uppercut'''
239 = '''se_m_stat_increase'''
240 = '''se_m_heat_wave'''
241 = '''se_m_uproar'''
242 = '''se_m_hail'''
243 = '''se_m_cosmic_power'''
244 = '''se_m_teeter_dance'''
245 = '''se_m_stat_decrease'''
246 = '''se_m_haze'''
247 = '''se_m_hyper_beam2'''
349 = '''mus_stop'''
350 = '''mus_littleroot_test'''
351 = '''mus_gsc_route38'''
352 = '''mus_caught'''
353 = '''mus_victory_wild'''
354 = '''mus_victory_gym_leader'''
355 = '''mus_victory_league'''
356 = '''mus_c_comm_center'''
357 = '''mus_gsc_pewter'''
358 = '''mus_c_vs_legend_beast'''
359 = '''mus_route101'''
360 = '''mus_route110'''
361 = '''mus_route120'''
362 = '''mus_petalburg'''
363 = '''mus_oldale'''
364 = '''mus_gym'''
365 = '''mus_surf'''
366 = '''mus_petalburg_woods'''
367 = '''mus_level_up'''
368 = '''mus_heal'''
369 = '''mus_obtain_badge'''
370 = '''mus_obtain_item'''
371 = '''mus_evolved'''
372 = '''mus_obtain_tmhm'''
373 = '''mus_lilycove_museum'''
374 = '''mus_route122'''
375 = '''mus_oceanic_museum'''
376 = '''mus_evolution_intro'''
377 = '''mus_evolution'''
378 = '''mus_move_deleted'''
379 = '''mus_encounter_girl'''
380 = '''mus_encounter_male'''
381 = '''mus_abandoned_ship'''
382 = '''mus_fortree'''
383 = '''mus_birch_lab'''
384 = '''mus_b_tower'''
385 = '''mus_encounter_swimmer'''
386 = '''mus_cave_of_origin'''
387 = '''mus_obtain_berry'''
388 = '''mus_awaken_legend'''
389 = '''mus_slots_jackpot'''
390 = '''mus_slots_win'''
391 = '''mus_too_bad'''
392 = '''mus_roulette'''
393 = '''mus_link_contest_p1'''
394 = '''mus_link_contest_p2'''
395 = '''mus_link_contest_p3'''
396 = '''mus_link_contest_p4'''
397 = '''mus_encounter_rich'''
398 = '''mus_verdanturf'''
399 = '''mus_rustboro'''
400 = '''mus_poke_center'''
401 = '''mus_route104'''
402 = '''mus_route119'''
403 = '''mus_cycling'''
404 = '''mus_poke_mart'''
405 = '''mus_littleroot'''
406 = '''mus_mt_chimney'''
407 = '''mus_encounter_female'''
408 = '''mus_lilycove'''
409 = '''mus_route111'''
410 = '''mus_help'''
411 = '''mus_underwater'''
412 = '''mus_victory_trainer'''
413 = '''mus_title'''
414 = '''mus_intro'''
415 = '''mus_encounter_may'''
416 = '''mus_encounter_intense'''
417 = '''mus_encounter_cool'''
418 = '''mus_route113'''
419 = '''mus_encounter_aqua'''
420 = '''mus_follow_me'''
421 = '''mus_encounter_brendan'''
422 = '''mus_ever_grande'''
423 = '''mus_encounter_suspicious'''
424 = '''mus_victory_aqua_magma'''
425 = '''mus_cable_car'''
426 = '''mus_game_corner'''
427 = '''mus_dewford'''
428 = '''mus_safari_zone'''
429 = '''mus_victory_road'''
430 = '''mus_aqua_magma_hideout'''
431 = '''mus_sailing'''
432 = '''mus_mt_pyre'''
433 = '''mus_slateport'''
434 = '''mus_mt_pyre_exterior'''
435 = '''mus_school'''
436 = '''mus_hall_of_fame'''
437 = '''mus_fallarbor'''
438 = '''mus_sealed_chamber'''
439 = '''mus_contest_winner'''
440 = '''mus_contest'''
441 = '''mus_encounter_magma'''
442 = '''mus_intro_battle'''
443 = '''mus_weather_kyogre'''
444 = '''mus_weather_groudon'''
445 = '''mus_sootopolis'''
446 = '''mus_contest_results'''
447 = '''mus_hall_of_fame_room'''
448 = '''mus_trick_house'''
449 = '''mus_encounter_twins'''
450 = '''mus_encounter_elite_four'''
451 = '''mus_encounter_hiker'''
452 = '''mus_contest_lobby'''
453 = '''mus_encounter_interviewer'''
454 = '''mus_encounter_champion'''
455 = '''mus_credits'''
456 = '''mus_end'''
457 = '''mus_vs_wild'''
458 = '''mus_vs_aqua_magma'''
459 = '''mus_vs_trainer'''
460 = '''mus_vs_gym_leader'''
461 = '''mus_vs_champion'''
462 = '''mus_vs_regi'''
463 = '''mus_vs_kyogre_groudon'''
464 = '''mus_vs_rival'''
465 = '''mus_vs_elite_four'''
466 = '''mus_vs_aqua_magma_leader'''
467 = '''mus_gsc_radio_tower_takeover'''


[[GotoShortcut]]
Name = '''Pokemon'''
Image = '''graphics.pokemon.sprites.front/350/sprite/'''
Destination = '''data.pokemon.stats/1'''

[[GotoShortcut]]
Name = '''Trainers'''
Image = '''graphics.trainers.sprites.front/3/sprite/'''
Destination = '''data.trainers.stats'''

[[GotoShortcut]]
Name = '''Moves'''
Image = '''graphics.moves.particles.sprites/55/ptr/'''
Destination = '''data.pokemon.moves.stats.battle'''

[[GotoShortcut]]
Name = '''Items'''
Image = '''graphics.overworld.sprites/59/data/0/sprites/0/sprite/'''
Destination = '''data.items.stats'''

[[GotoShortcut]]
Name = '''Maps'''
Image = '''data.maps.banks/0/maps/9/map/0/layout/0/blockmap/'''
Destination = '''maps.0-9 (LITTLEROOTTOWN)'''
